include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
